version: '3.8'

services:
  log-monitor:
    build:
      context: ./log-monitor
    container_name: log-monitor
    ports:
      - "8080:8080"
    restart: always
    networks:
      - monitoring_network  

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitoring_network 

networks:
  monitoring_network: 
    driver: bridge
